### ISSUE TITLE
Manifest links the wrong github url

### ISSUE THREAD

**Issue by ressu** [helfrichmichael/unraid-templates#2]
I noticed this when I was originally trying to track down the repository: https://github.com/helfrichmichael/unraid-templates/blob/3968de45189dde4b3d31c7992e1a2b59ce50d161/pruaslicer/prusaslicer.xml#L16

I think it should say https://github.com/helfrichmichael/prusaslicer-novnc instead. There are 2 occurrences of the URL in the same file.

**Comment by helfrichmichael** [comment]
This was fixed in d7e02ec87d30db7bbb502022bc985a9f9a4d9b26. Thanks for catching this, @ressu !

**Comment by ressu** [comment]
The second occurrence of the URL still seems to be there: https://github.com/helfrichmichael/unraid-templates/blob/d7e02ec87d30db7bbb502022bc985a9f9a4d9b26/pruaslicer/prusaslicer.xml#L32

**Comment by helfrichmichael** [comment]
Oops. I forgot the description is duplicated in the template.

I fixed this in 512a00868efe630cc938a26ace16d3fb70de2d18. Thanks again, @ressu !
